on:  
  push:
    branches:
      - develop

name: Deployment

jobs:
  deploy_dev:
    if: ${{ contains(github.ref, 'develop') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@v2
    - name: Setup NodeJS ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: 'Deploy from ${{ github.ref }} branch'
      run: |
         npm ci
         npm run build --if-present
         npm install serverless -g
         az login -u ${{ secrets.AZURE_USER }} -p ${{ secrets.AZURE_PASS }}
         curl https://raw.githubusercontent.com/serverless/serverless-azure-functions/master/scripts/generate-service-principal.sh -o sp.sh
         chmod +x sp.sh
         ./sp.sh
         source .env.servicePrincipal
         sls deploy --stage ${{ secrets.AZURE_DEV }} -i ${{ secrets.AZURE_SUB }} -g ${{ secrets.AZURE_RG }} --region ${{ secrets.AZURE_REGION }} --mongo_user ${{ secrets.MONGO_USER }} --mongo_pwd ${{ secrets.MONGO_PWD }} --mongo_db_name ${{ secrets.MONGO_DB_NAME }} --mongo_host ${{ secrets.MONGO_HOST }}

